# Generated by Django 4.1.7 on 2023-03-15 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.UUID('67032892-c763-4cc8-a075-bec28fac15a2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('create_date', models.DateField(auto_now=True)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('death_date', models.DateField(verbose_name='Date of Death')),
            ],
        ),
    ]
